### PR TITLE
Added crashlytics

### PR DESCRIPTION
**Pull request by sohilpandya**
We've added crashlytics to the app for better logs. 🤞 
related to #48 

Please review and merge after #45

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@sohilpandya good plan. Crashlytics is a _really_ good service for native dev. look forward to seeing feedback in our iOS standup! 👍

**Review by iteles — COMMENTED** [review]
Sorry to be a pain but I'd love to see a line added to the readme on crashlytics for this one 😊

**Comment by sohilpandya** [comment]
Hey @iteles, I've made that addition in the release-notes.md file, does that work?

**Comment by iteles** [comment]
It does, though would generally be nice to have a section on'tools' in the readme :+1:

**Pull request merged**
