### PR TITLE
Changed name of the app to dwyl time

### PR DESCRIPTION
**Pull request by sohilpandya**
Changed the name of the app from `time` to `dwyl time` 

related to #42 

Please Merge after #41. Not much to review as it's mainly me having to reset certain files paths and connections in Storyboard to get it all up and working again.

### CODE REVIEW

**Comment by nelsonic** [comment]
@sohilpandya I would prefer to just call the app `dwyl`. 
The fact that the _first **feature**_ we are building is _time_ does not need to be reflected in the name of the app.

**Comment by sohilpandya** [comment]
OK, I'll make that change and put an update out here.

**Comment by nelsonic** [comment]
@sohilpandya I don't meant to "block" your progress. just think that if the `dwyl` name is available on the App Store we should just use it. 👍 
(_keep up the great work BTW!!_)

**Comment by sohilpandya** [comment]
As a stopgap I've changed the name of the app on iTunes Connect, but kept the name the same for the XCode project as that will be slightly more time consuming. 👍

**Review by nelsonic — APPROVED** [review]
@sohilpandya thanks for updating the name in iTunes Connect. PR looks good. 👍

**Review by iteles — APPROVED** [review]
Agreed that if it's available, let's take it before anyone else does 😊

**Pull request merged**
