### PR TITLE
Added complications to the watch

### PR DESCRIPTION
**Pull request by sohilpandya**
- added modular small and modular large complications. 
- Please don't review the core data files, I've had to modify them to make it work with beta software, majority of the work is done in the apple watch side of things in this commit https://github.com/dwyl/time-apple-watch-app/commit/1f26dbc3b22a8dc0e076499e5c94b62503f5a93d

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@sohilpandya Looks good!
(_great to see older - no longer needed - code purged_) 👍

**Comment by sohilpandya** [comment]
I've just removed @iteles as an asignee as the app seems to be crashing on my phone and does not start. So let me figure out the issue before proceeding with merging this PR in.

**Comment by sohilpandya** [comment]
I came across a couple of issues:
- We have changed the name of the database to dwyl from time, this change did not take place in the app-delegate file. A part of the auto-generated code needed to be changed. 
- Apple Watch and iPhone were not syncing the tasks when a new one was added. I had to create a. fetch request for this to be in sync. 

Taken an additional T4h on top due to these two issues.

Uploaded build 21 to Beta store and pushing the new code onto the PR.

**Comment by sohilpandya** [comment]
@nelsonic would be good if you could look at the new changes in the commit https://github.com/dwyl/time-apple-watch-app/pull/93/commits/97fa02979e1b8db0cd959373e056289d1e05756b 

Please ignore the print statements, they've been removed in the following commit.

**Review by iteles — APPROVED** [review]
Apple watch still charging but looking forward to testing this!!

**Pull request merged**
